name: Deploying CKStatic01_

on:
  push:
    branches:
      - v1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploying to heroku
        id: deploy
        uses: akhileshns/heroku-deploy@v3.6.8

        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ckstatic01"
          heroku_email: "mebmdev2020@gmail.com"
